### ISSUE TITLE
Pushできない問題

### ISSUE THREAD

**Issue by t-ose** [siriusformalhaut/Parks#2]
プッシュかけると、エラーが出る。

$ git push origin master
remote: Permission to siriusformalhaut/Parks.git denied to t-ose.
fatal: unable to access 'https://github.com/siriusformalhaut/Parks.git/': The requested URL returned error: 403

たぶん、権限が私のアカウントにないため。

**Comment by siriusformalhaut** [comment]
そもそもpullもできなかった。。
公開鍵認証がうまくいってなさそうなエラーが出てるのでその辺かと。
調査します。

**Comment by siriusformalhaut** [comment]
コラボレーターに各位が入っていなかったあたりが原因かと。
追加してみたので再度試してもらえますか?

**Comment by KenMiz** [comment]
対応、ありがとう!!

2018/11/24 15:16、y-tanaka <notifications@github.com>のメール:

**Comment by t-ose** [comment]
pushできました。ありがとう！
